### ISSUE TITLE
Default Hit Sounds for Gems

### ISSUE THREAD

**Issue by TheToimeWulf** [gryttr/KAGIC#3]
[Found on KAGIC 1.10.0 A1, 11/9/2017]

Attacking any gem (including the Diamonds) will play the default hit sounds (including the critical hit) rather than sound clips played such as those in the 1.9 versions.

All gems are effected, however poofing voice lines, and shattering sounds are still there.

**Comment by gryttr** [comment]
Fixed in A4.
