### ISSUE TITLE
Topazes Without Texture

### ISSUE THREAD

**Issue by TheToimeWulf** [gryttr/KAGIC#4]
![2017-09-11_21 05 55](https://user-images.githubusercontent.com/31873444/30307797-1f67996c-973e-11e7-9240-6bd61f2e68af.png)
[Image shown above is of tamed Amethysts attacking the Topaz in question]

[Found on KAGIC 1.10.0 A1, 11/9/2017]
While fighting the Yellow Diamond boss, Topazes without textures spawn occaisionally. It seems to be random, as I have fought three separate bosses when two out of three had spawned texture-less Topazes before they were poofed.
Around 4 out of 10 topazes in the first instance were without texture.
The second instance had 2 out of 7 topaz.
The last produced no results.

**Comment by gryttr** [comment]
Fixed in A2.
